[package]
name = "maptch-client"
version = "0.0.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
crc = "3.0.1"
json = "0.12.4"
yaml-rust = "0.4.5"
config_template_derive = { path = "../config_template_derive" }
